#!/bin/sh

PWD=`pwd`
HOMEDIR=/home/`whoami`
BASENAME=`basename ${PWD}`
SCRIPT_DIR=`dirname ${BASH_SOURCE[0]}`

DOCKER_UID=`id -u`
DOCKER_GID=`id -g`
DOCKER_USERNAME=`whoami`
DOCKER_IMAGE_TAG=devenv:latest

if [ ! "`docker image ls -q ${DOCKER_IMAGE_TAG}`" ]; then
    docker build \
        --rm \
        -t ${DOCKER_IMAGE_TAG} \
        --build-arg UID=${DOCKER_UID} \
        --build-arg GID=${DOCKER_GID} \
        --build-arg USERNAME=${DOCKER_USERNAME} \
        ${SCRIPT_DIR}
fi

if [ "`docker container ls -aq -f \"name=devenv-${BASENAME}\"`" ]; then
    docker start devenv-${BASENAME}
    docker exec -ti devenv-${BASENAME} /bin/bash
else
    docker run \
        -it \
        --name devenv-${BASENAME} \
        -u `id -u`:`id -g` \
        -v ${PWD}:${HOMEDIR}/${BASENAME} \
        -w ${HOMEDIR}/${BASENAME} \
        -v ~/.vim:${HOMEDIR}/.vim \
        -v ~/.vimrc:${HOMEDIR}/.vimrc \
        -v ~/.tmux.conf:${HOMEDIR}/.tmux.conf \
        ${DOCKER_IMAGE_TAG}
fi
