#!/bin/sh

if [ "$#" -ne 1 ]; then
    echo "USAGE: $0 <dirname>"
    exit 1
fi

if [ "$(git -C $1 rev-parse --is-inside-work-tree 2> /dev/null)" != "true" ]; then
    basename $1
    exit 0
fi

GITDIR="$(git -C $1 rev-parse --show-toplevel)"
BASENAME="$(basename ${GITDIR})"

if [ "${BASENAME}" = "master" ]; then
    PARENT=$(dirname ${GITDIR})
    BASENAME=$(basename $PARENT)/m
fi

echo ${BASENAME}
